apiVersion: v1
kind: Secret
metadata:
  name: hubble-proposer-provider-url
data:
  # This is the base64 encoded provider url for geth
  # echo -n "http://geth:8545" | base64
  providerUrl: aHR0cDovL2dldGg6ODU0NQ==