apiVersion: v1
kind: Secret
metadata:
  name: hubble-proposer-provider-url
data:
  # This is where you would put your base64 encoded provider url
  # echo -n "https://foo.bar.com" | base64
  providerUrl: ...