# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ fork-master ]
  pull_request:
    branches: [ fork-master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run lint && npm run solhint
    - run: npm run generate
    - run: npm run keyless:check -- --offline
    - run: npm run test -- test/fast/*
    - run: npm run test -- test/slow/*
    - run: npm run test -- test/integration.test.ts
    - run: npm run bench

  cloc:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install cloc -y
    - run: cloc --exclude-dir test ./contracts
